### ISSUE TITLE
Add caching to smart meter blockchain calls

### ISSUE THREAD

**Issue by Norbo11** [levex/group-project#70]
Right now we have some functions defined in meter/blockchain.js which call stuff from contracts.

The front end is supposed to make calls to smart meter endpoints like /my_buyer_contracts/ in order to get this data into the dapp.

However, what's the point of doing this, if we can just import blockchain.js and call those functions directly?

The answer is obviously that the smart meter would add some extra functionality to those endpoints. One idea is to cache blockchain calls, for performance.

**Comment by fangyi-zhou** [comment]
> However, what's the point of doing this, if we can just import blockchain.js and call those functions directly?

You can.

Caching is definitely something we should do for performance reasons, but needs extra human-effort.

**Comment by fangyi-zhou** [comment]
#95 is first step

Subsequent steps:
- Update front end/back end APIs to accommodate this change
- Update Back End blockchain code to subscribe to contracts
- Write tests

**Comment by fangyi-zhou** [comment]
We might wish to use #77 as well, but I don't see a priority of doing that at the moment
