### ISSUE TITLE
meter: Make my_buyer_contracts and my_seller_contracts return contract addresses only

### ISSUE THREAD

**Issue by Norbo11** [levex/group-project#71]
This is so that we can simply look them up in our state.contracts instead of having to make a bunch of extra calls to blockchain

**Comment by fangyi-zhou** [comment]
Where do you get contracts from?

**Comment by fangyi-zhou** [comment]
This is a different model. We don't want to cache data from front end. So we might not want to do this. If someone else agrees we should close this

**Comment by danzvara** [comment]
Yep, closing.
