### ISSUE TITLE
meter: Re-write python API in node

### ISSUE THREAD

**Issue by Norbo11** [levex/group-project#73]
Right now we have a Python Eve server which serves as our smart meter DB... and also a Node server which serves as our blockchain API... we should probably merge the two. Unless we keep them seperate?

Won't take long if you use something like http://docs.sequelizejs.com/ and SQLite, because fuck Mongo

**Comment by fangyi-zhou** [comment]
We considered to deprecate python server and move everything to node. Yet we forgot about eve. Once again we need too much human effort which we didn't have.

**Comment by fangyi-zhou** [comment]
Priority high because it has dependent parts

**Comment by fangyi-zhou** [comment]
@levex is introducing new technology to address this, closing
